### ISSUE TITLE
Crash when attempting to explain query

### ISSUE THREAD

**Issue by dandv** [tart/motop#19]
``` text
Server           Opid     Client           Type   Sec   Locks                          Namespace                      Query
localhost:27017  8364     127.0.0.1:41645  query  7                                    stockbase-prod.content         {"sort": [["pubDate", -1], ["title", 1]], "spec": {"$or"


Server: localhost:27017
Opid: 8364
Sort: pubDate: -1, title: 1
Spec: {
    "$or": [
        {
            "cik": "0000055135"
        },
        {
            "companyId": "FT6ya7JvZzoL9hiNW"
        },
        {
            "companies.stockbase.matched._id": "FT6ya7JvZzoL9hiNW"
        },
        {
            "companies.calais.matched._id": "FT6ya7JvZzoL9hiNW"
        },
        {
            "companies.alchemy.matched._id": "FT6ya7JvZzoL9hiNW"
        }
    ],
    "pubDate": {
        "$gt": {
            "$date": -2206281600000
        }
    }
}
Traceback (most recent call last):
  File "/usr/local/bin/motop", line 5, in <module>
    pkg_resources.run_script('motop==4.1', 'motop')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/motop-4.1-py2.7.egg/EGG-INFO/scripts/motop", line 4, in <module>
    motop.run()
  File "/usr/local/lib/python2.7/dist-packages/motop-4.1-py2.7.egg/libmotop/motop.py", line 95, in run
    queryScreen.action()
  File "/usr/local/lib/python2.7/dist-packages/motop-4.1-py2.7.egg/libmotop/queryscreen.py", line 324, in action
    if not self.__operationBlock.explainQuery(*inputValues):
  File "/usr/local/lib/python2.7/dist-packages/motop-4.1-py2.7.egg/libmotop/queryscreen.py", line 272, in explainQuery
    return query.printExplain(line[0], line[6])
  File "/usr/local/lib/python2.7/dist-packages/motop-4.1-py2.7.egg/libmotop/queryscreen.py", line 184, in printExplain
    explainOutput = server.explainQuery(ns, self.__parts)
  File "/usr/local/lib/python2.7/dist-packages/motop-4.1-py2.7.egg/libmotop/server.py", line 126, in explainQuery
    return self.__execute(cursor.explain)
  File "/usr/local/lib/python2.7/dist-packages/motop-4.1-py2.7.egg/libmotop/server.py", line 64, in __execute
    return procedure(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo-2.7.1-py2.7-linux-x86_64.egg/pymongo/cursor.py", line 813, in explain
    return c.next()
  File "/usr/local/lib/python2.7/dist-packages/pymongo-2.7.1-py2.7-linux-x86_64.egg/pymongo/cursor.py", line 1038, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python2.7/dist-packages/pymongo-2.7.1-py2.7-linux-x86_64.egg/pymongo/cursor.py", line 982, in _refresh
    self.__uuid_subtype))
  File "/usr/local/lib/python2.7/dist-packages/pymongo-2.7.1-py2.7-linux-x86_64.egg/pymongo/cursor.py", line 925, in __send_message
    self.__compile_re)
  File "/usr/local/lib/python2.7/dist-packages/pymongo-2.7.1-py2.7-linux-x86_64.egg/pymongo/helpers.py", line 117, in _unpack_response
    compile_re)
  File "/usr/local/lib/python2.7/dist-packages/pymongo-2.7.1-py2.7-linux-x86_64.egg/bson/__init__.py", line 533, in decode_all
    tz_aware, uuid_subtype, compile_re))
  File "/usr/local/lib/python2.7/dist-packages/pymongo-2.7.1-py2.7-linux-x86_64.egg/bson/__init__.py", line 331, in _elements_to_dict
    data, position, as_class, tz_aware, uuid_subtype, compile_re)
  File "/usr/local/lib/python2.7/dist-packages/pymongo-2.7.1-py2.7-linux-x86_64.egg/bson/__init__.py", line 320, in _element_to_dict
    data, position, as_class, tz_aware, uuid_subtype, compile_re)
  File "/usr/local/lib/python2.7/dist-packages/pymongo-2.7.1-py2.7-linux-x86_64.egg/bson/__init__.py", line 159, in _get_object
    encoded, as_class, tz_aware, uuid_subtype, compile_re)
  File "/usr/local/lib/python2.7/dist-packages/pymongo-2.7.1-py2.7-linux-x86_64.egg/bson/__init__.py", line 331, in _elements_to_dict
    data, position, as_class, tz_aware, uuid_subtype, compile_re)
  File "/usr/local/lib/python2.7/dist-packages/pymongo-2.7.1-py2.7-linux-x86_64.egg/bson/__init__.py", line 320, in _element_to_dict
    data, position, as_class, tz_aware, uuid_subtype, compile_re)
  File "/usr/local/lib/python2.7/dist-packages/pymongo-2.7.1-py2.7-linux-x86_64.egg/bson/__init__.py", line 170, in _get_array
    as_class, tz_aware, uuid_subtype, compile_re)
  File "/usr/local/lib/python2.7/dist-packages/pymongo-2.7.1-py2.7-linux-x86_64.egg/bson/__init__.py", line 159, in _get_object
    encoded, as_class, tz_aware, uuid_subtype, compile_re)
  File "/usr/local/lib/python2.7/dist-packages/pymongo-2.7.1-py2.7-linux-x86_64.egg/bson/__init__.py", line 331, in _elements_to_dict
    data, position, as_class, tz_aware, uuid_subtype, compile_re)
  File "/usr/local/lib/python2.7/dist-packages/pymongo-2.7.1-py2.7-linux-x86_64.egg/bson/__init__.py", line 320, in _element_to_dict
    data, position, as_class, tz_aware, uuid_subtype, compile_re)
  File "/usr/local/lib/python2.7/dist-packages/pymongo-2.7.1-py2.7-linux-x86_64.egg/bson/__init__.py", line 170, in _get_array
    as_class, tz_aware, uuid_subtype, compile_re)
  File "/usr/local/lib/python2.7/dist-packages/pymongo-2.7.1-py2.7-linux-x86_64.egg/bson/__init__.py", line 159, in _get_object
    encoded, as_class, tz_aware, uuid_subtype, compile_re)
  File "/usr/local/lib/python2.7/dist-packages/pymongo-2.7.1-py2.7-linux-x86_64.egg/bson/__init__.py", line 331, in _elements_to_dict
    data, position, as_class, tz_aware, uuid_subtype, compile_re)
  File "/usr/local/lib/python2.7/dist-packages/pymongo-2.7.1-py2.7-linux-x86_64.egg/bson/__init__.py", line 320, in _element_to_dict
    data, position, as_class, tz_aware, uuid_subtype, compile_re)
  File "/usr/local/lib/python2.7/dist-packages/pymongo-2.7.1-py2.7-linux-x86_64.egg/bson/__init__.py", line 234, in _get_date
    dt = EPOCH_NAIVE + datetime.timedelta(seconds=seconds)
bson.errors.InvalidBSON: normalized days too large to fit in a C int
```

**Comment by hasegeli** [comment]
I have seen this one before but it was not reproducible.  Can you reproduce it?
