### ISSUE TITLE
connecting user based mongodb instance

### ISSUE THREAD

**Issue by thatsk** [tart/motop#26]
Traceback (most recent call last):
  File "/bin/motop", line 4, in <module>
    motop.run()
  File "/usr/lib/python2.7/site-packages/libmotop/motop.py", line 78, in run
    servers = commonServers(config, arguments)
  File "/usr/lib/python2.7/site-packages/libmotop/motop.py", line 67, in commonServers
    return [Server(section, **dict(config.items(section))) for section in config.sections()]
  File "/usr/lib/python2.7/site-packages/libmotop/server.py", line 30, in __init__
    self.tryToConnect()
  File "/usr/lib/python2.7/site-packages/libmotop/server.py", line 43, in tryToConnect
    self.__connection.admin.authenticate(self.__username, self.__password)
  File "/usr/lib64/python2.7/site-packages/pymongo/database.py", line 1048, in authenticate
    connect=True)
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 505, in _cache_credentials
    sock_info.authenticate(credentials)
  File "/usr/lib64/python2.7/site-packages/pymongo/pool.py", line 523, in authenticate
    auth.authenticate(credentials, self)
  File "/usr/lib64/python2.7/site-packages/pymongo/auth.py", line 470, in authenticate
    auth_func(credentials, sock_info)
  File "/usr/lib64/python2.7/site-packages/pymongo/auth.py", line 450, in _authenticate_default
    return _authenticate_scram_sha1(credentials, sock_info)
  File "/usr/lib64/python2.7/site-packages/pymongo/auth.py", line 201, in _authenticate_scram_sha1
    res = sock_info.command(source, cmd)
  File "/usr/lib64/python2.7/site-packages/pymongo/pool.py", line 419, in command
    collation=collation)
  File "/usr/lib64/python2.7/site-packages/pymongo/network.py", line 116, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/lib64/python2.7/site-packages/pymongo/helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Authentication failed.

**Comment by thatsk** [comment]
i have installed on centos instance and it has user based authentication to mongodb database but when i run motop it gives above error
