### ISSUE TITLE
motop 1.3 install via pypi failing

### ISSUE THREAD

**Issue by davecoutts** [tart/motop#7]
Install from egg via pypi. FAILS

``` python
dave@xxps:~$ mkvirtualenv motest -i motop
New python executable in motest/bin/python
Installing setuptools............done.
Installing pip...............done.
Downloading/unpacking motop
  Downloading motop-2.0.tar.gz
  Running setup.py egg_info for package motop
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/dave/.virtualenvs/motest/build/motop/setup.py", line 4, in <module>
        from src.Motop import Motop
    ImportError: No module named src.Motop
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/dave/.virtualenvs/motest/build/motop/setup.py", line 4, in <module>

    from src.Motop import Motop

ImportError: No module named src.Motop
```

Install from zip master via github. SUCCEEDS

``` python
dave@xxps:~$ mkvirtualenv motest -i https://github.com/tart/motop/archive/master.zip
New python executable in motest/bin/python
Installing setuptools............done.
Installing pip...............done.
Downloading/unpacking https://github.com/tart/motop/archive/master.zip
  Downloading master.zip
  Running setup.py egg_info for package from https://github.com/tart/motop/archive/master.zip

Downloading/unpacking pymongo (from motop==1.3)
  Downloading pymongo-2.5.tar.gz (294kB): 294kB downloaded
  Running setup.py egg_info for package pymongo

Installing collected packages: pymongo, motop
  Running setup.py install for pymongo
    building 'bson._cbson' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Ibson -I/usr/include/python2.7 -c bson/_cbsonmodule.c -o build/temp.linux-x86_64-2.7/bson/_cbsonmodule.o
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Ibson -I/usr/include/python2.7 -c bson/time64.c -o build/temp.linux-x86_64-2.7/bson/time64.o
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Ibson -I/usr/include/python2.7 -c bson/buffer.c -o build/temp.linux-x86_64-2.7/bson/buffer.o
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Ibson -I/usr/include/python2.7 -c bson/encoding_helpers.c -o build/temp.linux-x86_64-2.7/bson/encoding_helpers.o
    gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-2.7/bson/_cbsonmodule.o build/temp.linux-x86_64-2.7/bson/time64.o build/temp.linux-x86_64-2.7/bson/buffer.o build/temp.linux-x86_64-2.7/bson/encoding_helpers.o -o build/lib.linux-x86_64-2.7/bson/_cbson.so
    building 'pymongo._cmessage' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Ibson -I/usr/include/python2.7 -c pymongo/_cmessagemodule.c -o build/temp.linux-x86_64-2.7/pymongo/_cmessagemodule.o
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Ibson -I/usr/include/python2.7 -c bson/buffer.c -o build/temp.linux-x86_64-2.7/bson/buffer.o
    gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-2.7/pymongo/_cmessagemodule.o build/temp.linux-x86_64-2.7/bson/buffer.o -o build/lib.linux-x86_64-2.7/pymongo/_cmessage.so

  Running setup.py install for motop
    changing mode of build/scripts-2.7/motop.py from 664 to 775

    changing mode of /home/dave/.virtualenvs/motest/bin/motop.py to 775
Successfully installed pymongo motop
```

**Comment by hasegeli** [comment]
It was not version 1.3.  I broke it today for 15 minutes while trying setuptools on version2. I had not been aware that many people were using it.
